export const ActionTypes = {
   SELECT_POKEMON: "SELECT_POKEMON",
   REMOVE_SELECTED_POKEMON:"REMOVE_SELECTED_POKEMON",
   CACTCH_POKEMON: "CACTCH_POKEMON",
   CACTCH_POKEMON_t: "CACTCH_POKEMON_t",
   FREE_POKEMON: "FREE_POKEMON",
   FETCH_POKEMONS: "FETCH_POKEMONS",
   LOAD_FETCH_POKEMONS: "LOAD_FETCH_POKEMONS",
}